### ISSUE TITLE
Problem using Big.Rational as want in the verify

### ISSUE THREAD

**Issue by mikelangelon** [pascaldekloe/goe#1]
Using the verify function, works perfect except if a Big.Rat variable is found in the "want" parameter. For example, this struct give problems due to that value:

> &Effect{  
>                       InvoiceLineID:      400057,
>                       Value:              big.NewRat(200, 1),
>                       Spend:              big.NewRat(30, 1),  
>                   },

Also I'm attaching the log. 

Thanks :D

[bugBigRat.txt](https://github.com/pascaldekloe/goe/files/219306/bugBigRat.txt)

**Comment by pascaldekloe** [comment]
Go's reflection does not provide access to unexported fields. However, these arbitrary-precision numbers do implement encoding.TextMarshaller. I'll try a comparison fallback on the serial.

**Comment by pascaldekloe** [comment]
Can you give that one a try? :-)

**Comment by mikelangelon** [comment]
It works! Thanks :D
