### ISSUE TITLE
LICENSE file has no license

### ISSUE THREAD

**Issue by onlyjob** [pascaldekloe/goe#5]
[LICENSE](https://github.com/pascaldekloe/goe/blob/master/LICENSE) file contains no license.

The only relevant thing in there is

> To the extent possible under law, Pascal S. de Kloe has waived all copyright and related or neighboring rights to GoE.

Whatever "GoE" is (organisation?) the abose sentence disclaims copyright in favor of "GoE" and implicit "All Rights Reserverd" still applies.

Information related to licensing is in the `README.md` but it would be best to mention it in `LICENSE` file as well.

**Comment by pascaldekloe** [comment]
Your observations are correct. Since I waive all ownership I can't make any claims on what you can do with it. ;-) And GoE is the project you are looking at.

**Comment by onlyjob** [comment]
Please don't close bugs without resolution. `LICENSE` file should contain proper text of the license. This bug belongs here if it is an authoritative repository.

LICENSE should not be in conflict with the actual __CC0-1.0__ license (public domain waiver) from README.

Finally your reply raises concernes whether this code is free, as "All Rights Reserved" pretty much prohibits any use.

Just state the license in the LICENSE file, or duplicate public domain waiver there.

The conflict as I see it is that README disclaims copyright to the public domain while LICENSE disclaims copyright in favor of "GoE". Which one is true?

**Comment by pascaldekloe** [comment]
No, the license also explicitly waives any copyrights in that verry sentence you quoted.

You make a lot of statement. Is any of all that based on legal knowledge? In other words, is ther an issue preventing you from using the code in **any** way? Because that's the whole point of my efforts to publish in the first place.

**Comment by onlyjob** [comment]
Yes, based on some knowledge. There may be a practical problem with ambiguous license...
Your code may be introduced to Debian as part of _consul_ and we need to comply with DFSG requirements.

I think you may be using terms "public domain" and "GoE" as interchangable (when they are not). If you meant to put your code into public domain then just a CC waiver should be enough.

**Comment by pascaldekloe** [comment]
No "GoE" is this project's name. So the `LICENSE` file states that I [Pascal de Kloe] waives all copyrights to the project [GoE] and that the discard operation is possible from The Netherlands.
If you really think it should be different then please make a textual proposal and I'll check with a lawyer over here…
To be clear, you do think the README is fine as is, right?

**Comment by onlyjob** [comment]
Yes README is fine. There is no need to use two different (conflicting) waivers. The one in README is OK and the one in LICENSE is incorrent. I would copy waiver from README to LICENSE, replacing existing one in the LICENSE. Thanks.

**Comment by pascaldekloe** [comment]
The README does not waive the rights on itself by saying that it is public domain. That much even I know.

You repeat saying that the license is incorrect and conflicting. Can you elaborate on that? Or better, provide a pointer on how things should be.

**Comment by onlyjob** [comment]
I understand how frustrating it might be for you but please try to understand.
I've already explained everything above. License is not a license. Not much else to add.

README does wave rights by explicitly linking words "public domain" to https://creativecommons.org/publicdomain/zero/1.0/ which says:

> The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.

> You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.


Please put verbatim text of the _CC0-1.0_ as well as the URL of this document to the LICENSE file, replacing GoE waiver.

**Comment by pascaldekloe** [comment]
Sounds reasonable. The texts are similar in nature. I guess we can skip the last sentence. My lawyer will have a look tomorrow and if all's well then I'll modify all of my opensource projects accordingly.

**Comment by pascaldekloe** [comment]
Lawyer says no. The text from the link is needlessly vague and it is important to be specific about the origin locality.

I've followed "the tool" at https://creativecommons.org/publicdomain/ again and it recommends me to put the following snippet on the site. Note the text matches **exactly** with the content of the LICENSE file as is.

```html
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="https://licensebuttons.net/p/zero/1.0/80x15.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://github.com/pascaldekloe/goe">
    <span property="dct:title">Pascal S. de Kloe</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">Go Enterprice</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="NL" about="https://github.com/pascaldekloe/goe">
  Netherlands</span>.
</p>
```

So yes, the content of the LICENSE file is not a license (because I can't enforce a license without the copyrights) and no, there's no conflict or inconsistency. The README clearly explains the public domain nature with a reference and the LICENSE file correctly waives all copyrights.

I will change the GoE name to Go Enterprise, conform the README header to prevent confusion though.

**Comment by onlyjob** [comment]
The text from [the link](https://creativecommons.org/publicdomain/zero/1.0/) is a _summary_. In the very begginning of the document it have

> This is a human-readable summary of the [Legal Code (read the full text)](https://creativecommons.org/publicdomain/zero/1.0/legalcode).

Full text does not look too vague... Have you seen the full text?
https://creativecommons.org/publicdomain/zero/1.0/legalcode

Anyway, "Go Enterprice" != "public domain".  
Is "Go Enterprice" is a legal entity? If so then maybe including their contacts could help?

Thank you for using canonical text of CC0 waiver. However it is not specific enough to be recognised as such. It would be great if you could include URL of the CC0 waiver to the LICENSE file to serve the purpose of license identifier.

I doubt if "it is important to be specific about the origin locality" but I've never suggested to remove it.

Please consider adding the following URL to LICENSE file:

    https://creativecommons.org/publicdomain/zero/1.0/legalcode

Thank you.
