### ISSUE TITLE
please clarify copyright

### ISSUE THREAD

**Issue by onlyjob** [pascaldekloe/goe#6]
[README](../blob/master/README.md) and [LICENSE](../blob/master/LICENSE) have conflicting copyright statements.
Former claims that copyright is waived to "Public Domain" (i.e. there is no copyright) but the latter attribute copyright to [Go Enterprice](../blob/master/LICENSE#L2) (whatever it is).

Which is the correct one?

I sincerely hope that intention was to wave off copyright entirely, instead of assigning it to some misterious entity. Nothing relevant comes up when I search for "Go Enterprice"...

I recommend to replace "Go Enterprice" with "public domain" because "[Public Domain](https://en.wikipedia.org/wiki/Public_domain)" is a term that [CC0 waiver](https://creativecommons.org/publicdomain/zero/1.0/) refers to.

Thanks.

**Comment by pascaldekloe** [comment]
Ah, it's you again, from issue #5. I really don't know why you repeatedly fail to understand that Go Enterprise is the name of this project. 😆It does not state that copyrights are attributed to anyone. The precise text comes from creative commons. Fill out the CC0 form and see for yourself. If you know better than them, then prove it.

**Comment by onlyjob** [comment]
Yes, me again. You think I'm enjoying to nitpick on you?? The problem is valid -- how can you not be troubled by inconsistency?? I must be so stupid not to understand something so obvious to you. :(
If you did not mean to refer to this project by different names then at least you've got to correct the typo: `Go Enterprice` --> `Go Enterprise`.

**Comment by pascaldekloe** [comment]
So are you going to take on this valid problem to the Creative Commons organisation? Happy to make an introduction, if that'd be of any help...?

**Comment by onlyjob** [comment]
Thanks for correcting typo. 

> So are you going to take on this valid problem to the Creative Commons organisation? Happy to make an introduction, if that'd be of any help...?

That sarcasm is unnecessary.

As far as I'm concerned, the only problem is inconsistency between README and LICENSE.
But whatever... Why should I care anyway... :(

IMHO LICENSE disclaimer is awkwardly worded but the text is generated by online [
CC0 Waiver](https://creativecommons.org/choose/zero/waiver) so there is nothing to improve...

**Comment by pascaldekloe** [comment]
Again, I've spelled out for you, like 3 times, that the text of LICENSE comes directly form Creative Commons. That is the reason I don't take your word for it, plus my lawyer said it's OK. However, if your legal knowledge says otherwise, then maybe seek a dialogue and find out? I'm trying to keep an open mind here.

**Comment by onlyjob** [comment]
My impression is that every time you were making good and necessary corrections with a lot of resistance and arguing. :) It took only 3 bug reports (#4, #5, #6) to make things better. ;)

**Comment by pascaldekloe** [comment]
I'm all in favour of improvement. Just not what you are asking. So again, are you going to make this valid point against the Creative Commons organisation? If not then why do you keep trying with me?

**Comment by onlyjob** [comment]
Now I'm confused what is that I'm asking that can not be done... Anyway, with your last change I think everything is OK.
I don't know if I'm going to talk to CC about wording of the waiver any time soon.
I want to, but not sure when time allows me to do so.

I had to trouble you with changes because this library may be introduced to Debian and Debian DFSG compliance review is vigorous. I hope it was not too much inconvenience.

**Comment by pascaldekloe** [comment]
Nothing in this issue report, nor your previous one, was addressed. I've followed up on two of your side comments, namely adding a URL (why not) and correct a spelling typo. If you think it's OK now, then yes, it was way too much inconvenience.

**Comment by onlyjob** [comment]
I'm glad you've made those changes. Thank you.
I think it is not ideal but as good as it gets, given the circumstances.
Sorry for inconvenience but that was _necessary_. Your library is used by some serious projects and license clarity is a must.
